#!/bin/bash

DESKTOP_FILE=/opt/Discord/discord.desktop

# Download most recent version.
curl --output discord.tar.gz -L "https://discord.com/api/download?platform=linux&format=tar.gz"

# Unpack
sudo tar -xvzf discord.tar.gz -C /opt

# Symlink the executable to the binary executables directory.
sudo ln -sf /opt/Discord/Discord /usr/bin/Discord

# To be able to launch graphically we need to update the desktop file
# and copy it to the applications directory so the system can access it
sudo sed -i -e 's|Exec=.*$|Exec=/usr/bin/Discord|g' "$DESKTOP_FILE"
sudo sed -i -e "s|Icon=.*$|Icon=/opt/Discord/discord.png|g" "$DESKTOP_FILE"
sudo cp -r "$DESKTOP_FILE" /usr/share/applications

# Clean up
rm discord.tar.gz
